[tool.poetry]
name = "fsutils"
version = "0.1.0"
description = ""
authors = ["jMujunen <jMujunen@github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
chardet = "^5.2.0"
pillow = "^10.3.0"
pandas = "^2.2.2"
ollama = "^0.2.1"
imagehash = "^4.3.1"
opencv-python = "^4.10.0.84"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
