FILE_TYPES: dict[str, tuple] = {
    "img": (".jpg", ".jpeg", ".png", ".gif", ".nef", ".webp"),
    "config": (
        ".ini",
        ".xml",
        ".json",
        ".cfg",
        ".conf",
        ".yaml",
        ".yml",
        ".properties",
        ".bashrc",
        ".bash_profile",
        ".zshrc",
        ".vimrc",
        ".shellrc",
        ".condarc",
        ".xbindkeysrc",
        "kwinrc",
        "breezerc",
        "kdeglobals",
        "plasmarc",
        "kglobalshortcutsrc",
        "kwinrulesrc",
    ),
    "img_other": (".heatmap", ".ico", ".svg", ".heic"),
    "metadata": (".lrprev", ".xml", ".aae", ".exif", ".iptc", ".tiff", ".xmp", ".pp3"),
    "doc": (".pdf", ".doc", ".docx", ".odt", ".pptx"),
    "video": (".mp4", ".avi", ".mkv", ".wmv", ".webm", ".m4v", ".flv", ".mpg", ".mov"),
    "audio": (
        ".3ga",
        ".aac",
        ".ac3",
        ".aif",
        ".aiff",
        ".alac",
        ".amr",
        ".ape",
        ".au",
        ".dss",
        ".flac",
        ".flv",
        ".m4a",
        ".m4b",
        ".m4p",
        ".mp3",
        ".mpga",
        ".ogg",
        ".oga",
        ".mogg",
        ".opus",
        ".qcp",
        ".tta",
        ".voc",
        ".wav",
        ".wma",
        ".wv",
    ),
    "zip": (
        ".zip",
        ".rar",
        ".tar",
        ".bz2",
        ".7z",
        ".gz",
        ".xz",
        ".tar.gz",
        ".tgz",
        ".zipx",
    ),
    "raw": (".cr2", ".raf", ".dng", ".raf"),
    "log": (".csv", ".json", ".log"),
    "txt": (".txt", ".md", ".out", ".note"),
    "script": (
        ".py",
        ".bat",
        ".sh",
        ".c",
        ".cpp",
        ".h",
        ".java",
        ".js",
        ".ts",
        ".php",
        ".html",
        ".css",
        ".scss",
        ".ps1",
        ".qml",
    ),
    "binary": (
        ".dat",
        ".db",
        ".dbf",
        ".mdb",
        ".sqlite",
        ".sqlite3",
        ".exe",
        ".mdat",
        ".thp",
        ".jar",
        ".mca",
        ".package",
        ".class",
    ),
    "trash": (
        ".directoryStoreFile",
        ".indexArrays",
        ".indexBigDates",
        ".indexCompactDirectory",
        ".indexDirectory",
        ".indexGroups",
        ".indexHead",
        ".indexIds",
        ".indexPositions",
        ".indexPostings",
        ".indexUpdates",
        ".shadowIndexGroups",
        ".shadowIndexHead",
        ".indexPositionTable",
        ".indexTermIds",
        ".shadowIndexArrays",
        ".shadowIndexCompactDirectory",
        ".shadowIndexDirectory",
        ".shadowIndexTermIds",
        ".updates",
        ".rmskin",
        ".GITGUI_MSG",
        ".COMMIT_EDITMSG",
        ".ORIG_HEAD",
        ".HEAD",
        ".MASTER",
        ".FETCH_HEAD",
        ".packed-refs",
        ".index",
        ".commit-graph",
        ".packs",
        ".refs",
        ".exclude",
        ".master",
        ".remote",
        ".temp",
        ".recovery",
        ".description",
        ".so",
        ".pyc",
        ".iso",
        ".trashinfo",
        ".torrent",
        ".bin",
        ".lnk",
        ".plist",
        ".shadow",
        ".loc",
        ".state",
        ".37",
        ".cachedmsg",
        ".git",
        ".jar",
        ".dll",
        ".package",
        ".ini",
        ".sha1",
        ".DayZProfile",
        ".dat_old",
        ".lock",
        ".list",
        ".glob",
        ".blueprint",
        ".rxr",
        ".ver1",
        ".pyi",
        ".whl",
        ".metadata",
        ".pickle",
        ".so",
    ),
    "ignored": (".xml",),
    "dupes": (),  # For duplicate files
}
IGNORED_DIRS = ("site-packages", ".Trash-info", ".git", "venv", ".venv", ".cache")
